#!/bin/bash

echo 'Rede: ' $1
echo 'Mail: ' $2
echo 'Hash: ' $3

cd /var/www

cp tcd.config $3_tcd.config

HOST='server2.megamidia.com.br'
USER='tcd_offline'
PASSWD='M3g4tcd2013'
FILE='put '$3'_tcd.config'
MAIL=''

if [ $2 == 1 ]
then
cp mail.config $3_mail.config
	MAIL='put '$3'_mail.config'
fi
 
ftp -n $HOST <<END_SCRIPT
quote user $USER
quote PASS $PASSWD
mkdir $1
cd $1
$FILE
$MAIL
quit
END_SCRIPT