#!/usr/bin/expect

## 4 horas de janela
set timeout 14400

spawn /bin/sh -c "rsync -LCravzp radiob@server2.megamidia.com.br:/home/redes/<rede>/ /var/www/"
expect {
    timeout {
        exit 1
    }
    -re "lost" {
        exit 1
    }
    -re "No route to host" {
        exit 1
    }
    -re "continue connecting" {
    	send "yes\r"
        exp_continue
        exit 0
    }
    -re "radiob@server2.megamidia.com.br's password:" {
        send "radiob\r"
        exp_continue
        exit 0
    }
}

spawn python /var/www/tcd_offline/setup.py <rede>
expect